caronte/details/urls.py
"""Details urls."""

# Django
from django.urls import path
# Project
from caronte.details.views import CreateDetailView


urlpatterns = [
    path('create/', CreateDetailView.as_view(), name='create'),
]

caronte/index/urls.py
"""Index urls module."""

# Django
from django.urls import path
# Project
from .views import MainView


urlpatterns = [
    path('', MainView.as_view(), name='main'),
]

caronte/users/urls.py
# Django
from django.urls import path
# Project
from .views import LoginView, LogoutView, SignupView, set_theme_view


urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('set_theme/<str:theme>/', set_theme_view, name='set_theme')
]

config/urls.py
# Django
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('caronte.index.urls', 'index'), namespace='index')),
    path('details/', include(('caronte.details.urls', 'details'), namespace='details')),
    path('periods/', include(('caronte.periods.urls', 'periods'), namespace='periods')),
    path('users/', include(('caronte.users.urls', 'users'), namespace='users')),
]

caronte/dailies/models/dailies.py
"""Dailies models module."""

# Django
from django.db import models
from django.utils import timezone
# Project
from caronte.details.models import Detail
from caronte.periods import services as period_services
from caronte.periods.models import Period
from caronte.utils.models import BaseModel


class DailyManager(models.Manager):

    @staticmethod
    def from_today(period: Period):
        """
        Look for current Daily or create a new if it does not exists.
        Refresh current Period status if a new Daily has been created.

        :param period: User's Period to search today's Daily.
        :return: Today's Daily with its current Details list.
        """

        daily = None

        if period is not None:
            today = timezone.now().date()
            get_or_create = Daily.objects.get_or_create(period=period, date=today, defaults={
                'period': period,
                'expense': 0,
                'remainder': period.daily_budget
            })
            daily, created = get_or_create[0], get_or_create[1]
            daily.details = Detail.objects.filter(daily=daily)
            period.dailies = Daily.objects.filter(period=period)
            if created:
                period = period_services.refresh(period)

        return period, daily


class Daily(BaseModel):

    period = models.ForeignKey('periods.Period', on_delete=models.CASCADE)

    notes = models.CharField(max_length=1000, blank=True, null=True)

    date = models.DateField()

    expense = models.DecimalField(max_digits=9, decimal_places=2)

    remainder = models.DecimalField(max_digits=9, decimal_places=2)

    balance = models.DecimalField(max_digits=9, decimal_places=2, null=False, blank=True, default=0)

    objects = DailyManager()

    @property
    def today_remainder(self):
        return self.period.daily_budget - self.expense

    class Meta(BaseModel.Meta):
        ordering = ['date']

caronte/details/models/detail.py
"""Details models module."""

# Django
from django.db import models
from django.utils import timezone
# Project
from caronte.utils.models import BaseModel


class Detail(BaseModel):

    daily = models.ForeignKey('dailies.Daily', on_delete=models.CASCADE)

    title = models.CharField(max_length=50)

    expense = models.DecimalField(max_digits=9, decimal_places=2)

    class Meta(BaseModel.Meta):
        ordering = ['created']

caronte/details/forms/detail.py
# Django
from django import forms
from django.utils.translation import gettext_lazy as _
# Project
from caronte.details.models import Detail
from caronte.utils.forms import IconCharField, IconDecimalField


class DetailForm(forms.ModelForm):

    class Meta:
        model = Detail
        fields = ['title', 'expense']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'] = IconCharField(icon='fas fa-pen', placeholder=_('Description'))
        self.fields['expense'] = IconDecimalField(icon='fas fa-dollar-sign', placeholder=_('Amount'))

caronte/periods/forms/periods.py
"""Periods forms."""

# Python
from datetime import datetime
# Django
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _
# Project
from caronte.periods.models import Period
from caronte.utils.forms import IconDecimalField, IconDateField


class PeriodForm(forms.ModelForm):

    class Meta:
        model = Period
        fields = ['finish_date', 'budget']

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.fields['finish_date'] = IconDateField(icon='fas fa-calendar-alt', placeholder=_('Finish date'))
        self.fields['budget'] = IconDecimalField(icon='fas fa-dollar-sign', placeholder=_('Budget'))

    def clean(self):
        now = datetime.now()
        split_date = self.cleaned_data.get('finish_date').split('-')
        existing_period = Period.objects.current(user=self.user)
        if existing_period:
            raise ValidationError(_('You already have an active Period'))
        errors = ''
        if datetime(int(split_date[0]), int(split_date[1]), int(split_date[2])) <= now:
            errors += _('Period finish date must be after today')
        if float(self.cleaned_data.get('budget')) < 30:
            if errors:
                errors += ', '
            errors += _('Budget cannot be less than $30')
        if errors:
            raise ValidationError(errors)

caronte/users/forms/login.py
# Django
from django import forms
from django.utils.translation import gettext_lazy as _
# Project
from caronte.utils.forms import IconCharField, IconPasswordField


class LoginForm(forms.Form):

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        self.fields['username'] = IconCharField(
            placeholder=_('Username'),
            icon='fas fa-user'
        )

        self.fields['password'] = IconPasswordField(
            placeholder=_('Password'), 
            icon='fas fa-key'
        )

caronte/users/forms/signup.py
# Django
from django import forms
from django.utils.translation import gettext_lazy as _
# Project
from caronte.users.models import User
from caronte.utils.forms import IconCharField, IconEmailField, IconPasswordField


class SignupForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password']

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        self.fields['username'] = IconCharField(
            placeholder=_('Username'),
            icon='fas fa-user-circle'
        )

        self.fields['email'] = IconEmailField(
            placeholder=_('Email'),
            icon='fas fa-at'
        )

        self.fields['first_name'] = IconCharField(
            placeholder=_('First name'),
            icon='fas fa-user-edit'
        )

        self.fields['last_name'] = IconCharField(
            placeholder=_('Last name'),
            icon='fas fa-user-edit'
        )

        self.fields['password'] = IconPasswordField(
            placeholder=_('Password'),
            icon='fas fa-key'
        )

        self.fields['re_password'] = IconPasswordField(
            placeholder=_('Password again'),
            icon='fas fa-key',
            required=False
        )

caronte/utils/forms/icon_fields.py
# Django
from django import forms


class IconCharField(forms.CharField):
    """Django CharField with custom icon attr."""
    
    def __init__(self, *, icon='', placeholder=None, max_length=None,
                 min_length=None, strip=True, empty_value='', **kwargs):
        super().__init__(**kwargs)
        self.icon = icon
        self.widget = forms.TextInput(attrs={'class': 'form-control'})
        if placeholder is not None:
            self.widget.attrs['placeholder'] = placeholder


class IconEmailField(forms.EmailField):
    """Django EmailField with custom icon attr."""
    
    def __init__(self, icon='', placeholder=None, **kwargs):
        super().__init__(**kwargs)
        self.icon = icon
        self.widget = forms.EmailInput(attrs={'class': 'form-control'})
        if placeholder is not None:
            self.widget.attrs['placeholder'] = placeholder


class IconPasswordField(forms.CharField):
    """Django CharField with custom icon attr and password widget."""
    
    def __init__(self, *, icon='', placeholder=None, max_length=None, 
                 min_length=None, strip=True, empty_value='', **kwargs):
        super().__init__(**kwargs)
        self.icon = icon
        self.widget = forms.PasswordInput(attrs={'class': 'form-control'})
        if placeholder is not None:
            self.widget.attrs['placeholder'] = placeholder


class IconDateField(forms.CharField):
    """Django CharField with custom icon attr for dates."""

    def __init__(self, *, icon='', placeholder=None, max_length=None,
                 min_length=None, strip=True, empty_value='', **kwargs):
        super().__init__(**kwargs)
        self.icon = icon
        self.widget = forms.DateInput(attrs={'class': 'form-control', 'type': 'date'})
        if placeholder is not None:
            self.widget.attrs['placeholder'] = placeholder


class IconDecimalField(forms.CharField):
    """Django NumberField with custom icon attr and two decimals."""

    def __init__(self, *, icon='', placeholder=None, max_length=None,
                 min_length=None, strip=True, empty_value='', **kwargs):
        super().__init__(**kwargs)
        self.icon = icon
        self.widget = forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01'})
        if placeholder is not None:
            self.widget.attrs['placeholder'] = placeholder

caronte/details/views/create.py
"""Create Detail views."""

# Django
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views.generic import View
# Project
from caronte.details import services
from caronte.details.forms import DetailForm
from caronte.utils.genericfunctions import form_errors_into_string


class CreateDetailView(View):

    form_model = DetailForm

    def get(self, request, *args, **kwargs):
        return redirect('index:main')

    def post(self, request, *args, **kwargs):
        form = self.form_model(data=request.POST)
        if not form.is_valid():
            errors = form_errors_into_string(form.errors)
            messages.warning(request, errors)
        else:
            detail = services.create(
                user=request.user,
                title=form.cleaned_data.get('title'),
                expense=form.cleaned_data.get('expense')
            )
            if detail:
                messages.success(request, _('Expense added'))
            else:
                messages.error(request, _('Unkown error occurred'))
        return redirect('index:main')

caronte/index/views.py
"""Index views module."""

# Python
import datetime
# Django
from django.shortcuts import render
from django.views import View
# Project
from caronte.details.forms import DetailForm
from caronte.index import services
from caronte.periods.forms import PeriodForm
from caronte.users.forms import SignupForm
from caronte.utils.constants.strings import CARONTE_INDEX_DESCRIPTION


class MainView(View):
    """
    Main view of the application. Display logic conditions are:
        Authenticated user:
            Existent current Period: the current Period, current Daily with its Details, and previous Dailies.
            No current Period: new Period creation template.
        Anonymous user:
            Application info with login an sign up forms.
    """

    period = None
    daily = None

    def get(self, request):
        """
        Handle get request of main index view page.
        If user is authenticated, look for current period, then if a current Period exists, look (or create a new)
        for the current Daily with its Details. If there is no current Period, the page will display a new Period
        form template to create and start a new one.

        @:return render index/main.html with the proper info and template.
        """

        self.period, self.daily = services.handle_index_view(request)

        return render(request, 'index/main.html', {
            'signup_form': SignupForm(),
            'period_form': PeriodForm(),
            'detail_form': DetailForm(),
            'CARONTE_INDEX_DESCRIPTION': CARONTE_INDEX_DESCRIPTION,
            'period': self.period,
            'daily': self.daily,
            'today': datetime.date.today(),
        })

caronte/periods/views/create.py
# Django
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views import View
# Project
from caronte.periods import services
from caronte.periods.forms import PeriodForm
from caronte.utils.genericfunctions import form_errors_into_string


class CreatePeriodView(View):

    form_class = PeriodForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(user=request.user, data=request.POST)
        if form.is_valid():
            period = services.create(
                user=request.user,
                finish_date=form.cleaned_data.get('finish_date'),
                budget=form.cleaned_data.get('budget')
            )
            if period:
                messages.success(request, _('Period started successfully'))
            else:
                messages.error(request, _('Unknown error occurred, please try again'))
        else:
            errors = form_errors_into_string(form.errors)
            messages.warning(request, errors)
        return redirect('index:main')

caronte/users/views/login.py
# Django
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views import View
# Project
from caronte.users import services
from caronte.users.forms import LoginForm


class LoginView(View):
    """Class that receives users' login request."""

    form_class = LoginForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST, prefix='login')
        if form.is_valid():
            user = services.login(
                request=request,
                username=form.cleaned_data.get('username'),
                password=form.cleaned_data.get('password')
            )
            if user is not None:
                messages.success(request, _('You have logged in'))
            else:
                messages.warning(request, _('Wrong username/password'))
        return redirect('index:main')

caronte/users/views/logout.py
# Django
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views import View
# Project
from caronte.users import services


class LogoutView(View):

    @staticmethod
    def get(request):
        if request.user.is_authenticated:
            services.logout(request)
            messages.success(request, _('You have logged out'))
        return redirect('index:main')

caronte/users/views/set_theme.py
# Django
from django.shortcuts import redirect
# Project
from caronte.users.models import User


def set_theme_view(request, theme):
    """
    Set user theme_option in session. Also set value to authenticated user's theme attribute and update user.
    :param request: Django's request
    :param theme: Option to set in session (a/l/d) -> (auto/light/dark)
    :return: redirect to the same page where the request came from, or index's main if theme option is corrupt.
    """
    request.session['theme_option'] = User.Theme(theme).name
    if request.user.is_authenticated:
        request.user.theme = User.Theme(theme)
        request.user.save()
    return redirect(request.META.get('HTTP_REFERER', 'index:main'))

caronte/users/views/signup.py
"""Users signup views."""

# Django
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views import View
# Project
from caronte.users import services
from caronte.users.forms import SignupForm
from caronte.utils.genericfunctions import form_errors_into_string


class SignupView(View):
    """Class that receives users' signup request."""

    form_class = SignupForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            user = services.signup(
                username=form.cleaned_data.get('username'),
                email=form.cleaned_data.get('email'),
                password=form.cleaned_data.get('password'),
                first_name=form.cleaned_data.get('first_name'),
                last_name=form.cleaned_data.get('last_name')
            )
            if user is not None:
                messages.success(request, _('You have registered your account'))
            else:
                messages.error(request, _('Something went wrong, please try again'))
        else:
            errors = form_errors_into_string(form.errors)
            messages.warning(request, errors)
        return redirect('index:main')

caronte/templates/index/main_authenticated/current_period/new_expense.html
{% load i18n %}

<h5 class="card-title">{% translate 'New expense' %}</h5>
<div class="card-text">
    <form action="{% url 'details:create' %}" method="POST" enctype="application/x-www-form-urlencoded">
        {% csrf_token %}
        {% for field in detail_form %}
            <div class="row justify-content-center">
                <div class="col-12 col-lg-4 my-1 mx-1">
                    <div class="input-group">
                        <div class="input-group-text">
                            <i class="{{ field.field.icon }} mx-auto"></i>
                        </div>
                        {{ field }}
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="row justify-content-center">
            <div class="col-12 col-lg-4 md-lg-4 my-1 mx-1">
                <div class="d-grid">
                    <button class="btn btn-success">{% translate 'Submit' %}</button>
                </div>
            </div>
        </div>
    </form>
</div>

caronte/templates/index/main_authenticated/current_period/previous_daily_summaries.html
{% load i18n %}

<h5 class="card-title">{% translate 'Previous daily summaries' %}</h5>
<div class="card-text table-responsive">
    <table class="table {% if request.session.theme.lower == 'dark' %}table-dark{% endif %} table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">{% translate 'Date' %}</th>
                <th scope="col">{% translate 'Spending' %}</th>
                <th scope="col">{% translate 'Remainder' %}</th>
                <th scope="col">{% translate 'Balance' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for daily in period.previous_dailies %}
                <tr>
                    <td scope="row"><span style="white-space: nowrap;">{{ daily.date|date:"d/m" }}</span></td>
                    <td><span style="white-space: nowrap;">$ {{ daily.expense|floatformat:2 }}</span></td>
                    <td><span style="white-space: nowrap;">$ {{ daily.remainder|floatformat:2 }}</span></td>
                    <td class="text-end"><span style="white-space: nowrap;">$ {{ daily.balance|floatformat:2 }}</span></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

caronte/templates/index/main_authenticated/current_period/today_expenses.html
{% load i18n %}


<h5 class="card-title">{% translate "Today's expenses" %}</h5>
<div class="card-text">
    <table class="table {% if request.session.theme.lower == 'dark' %}table-dark{% endif %} table-striped table-hover table-responsive-md">
        <thead>
            <tr>
                <th scope="col">{% translate 'Time' %}</th>
                <th scope="col">{% translate 'Description' %}</th>
                <th scope="col">{% translate 'Amount' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for detail in daily.details %}
            <tr>
                <td scope="row">{{ detail.created|time:"H:i" }}</td>
                <td>{{ detail.title }}</td>
                <td class="text-end px-md-3 px-1"><span style="white-space: nowrap;">$ {{ detail.expense|floatformat:2 }}</span></td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td>
                    <strong>{% translate 'Total' %}:<br><span style="white-space: nowrap;">$ {{ daily.expense|floatformat:2 }}</span></strong>
                </td>
                <td class="
                {% if daily.today_remainder < 0.00 %}
                    {% if request.session.theme.lower == 'dark' %}
                        text-red-strong
                    {% else %}
                        text-red
                    {% endif %}
                {% elif daily.today_remainder > 0.01 %}
                    {% if request.session.theme.lower == 'dark' %}
                        text-green-strong
                    {% else %}
                        text-green
                    {% endif %}
                {% endif %}
                ">
                    <strong>{% translate 'Remainder' %}:<br><span style="white-space: nowrap;">$ {{ daily.today_remainder|floatformat:2 }}</span></strong>
                </td>
                <td class="text-end
                {% if period.balance < 0.00 %}
                    {% if request.session.theme.lower == 'dark' %}
                        text-red-strong
                    {% else %}
                        text-red
                    {% endif %}
                {% elif period.balance > 0.01 %}
                    {% if request.session.theme.lower == 'dark' %}
                        text-green-strong
                    {% else %}
                        text-green
                    {% endif %}
                {% endif %}
                ">
                    <strong>{% translate 'Balance' %}:<br><span style="white-space: nowrap;">$ {{ period.balance|floatformat:2 }}</span></strong>
                </td>
            </tr>
        </tfoot>
    </table>
</div>