caronte/details/urls.py
"""Details urls."""

# Django
from django.urls import path
# Project
from caronte.details.views import CreateDetailView


urlpatterns = [
    path('create/', CreateDetailView.as_view(), name='create'),
]

caronte/index/urls.py
"""Index urls module."""

# Django
from django.urls import path
# Project
from .views import MainView


urlpatterns = [
    path('', MainView.as_view(), name='main'),
]

caronte/users/urls.py
# Django
from django.urls import path
# Project
from .views import LoginView, LogoutView, SignupView, set_theme_view


urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('set_theme/<str:theme>/', set_theme_view, name='set_theme')
]

config/urls.py
# Django
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('caronte.index.urls', 'index'), namespace='index')),
    path('details/', include(('caronte.details.urls', 'details'), namespace='details')),
    path('periods/', include(('caronte.periods.urls', 'periods'), namespace='periods')),
    path('users/', include(('caronte.users.urls', 'users'), namespace='users')),
]

caronte/dailies/models/dailies.py
"""Dailies models module."""

# Django
from django.db import models
from django.utils import timezone
# Project
from caronte.details.models import Detail
from caronte.periods import services as period_services
from caronte.periods.models import Period
from caronte.utils.models import BaseModel


class DailyManager(models.Manager):

    @staticmethod
    def from_today(period: Period):
        """
        Look for current Daily or create a new if it does not exists.
        Refresh current Period status if a new Daily has been created.

        :param period: User's Period to search today's Daily.
        :return: Today's Daily with its current Details list.
        """

        daily = None

        if period is not None:
            today = timezone.now().date()
            get_or_create = Daily.objects.get_or_create(period=period, date=today, defaults={
                'period': period,
                'expense': 0,
                'remainder': period.daily_budget
            })
            daily, created = get_or_create[0], get_or_create[1]
            daily.details = Detail.objects.filter(daily=daily)
            period.dailies = Daily.objects.filter(period=period)
            if created:
                period = period_services.refresh(period)

        return period, daily


class Daily(BaseModel):

    period = models.ForeignKey('periods.Period', on_delete=models.CASCADE)

    notes = models.CharField(max_length=1000, blank=True, null=True)

    date = models.DateField()

    expense = models.DecimalField(max_digits=9, decimal_places=2)

    remainder = models.DecimalField(max_digits=9, decimal_places=2)

    balance = models.DecimalField(max_digits=9, decimal_places=2, null=False, blank=True, default=0)

    objects = DailyManager()

    @property
    def today_remainder(self):
        return self.period.daily_budget - self.expense

    class Meta(BaseModel.Meta):
        ordering = ['date']

caronte/details/models/detail.py
"""Details models module."""

# Django
from django.db import models
from django.utils import timezone
# Project
from caronte.utils.models import BaseModel


class Detail(BaseModel):

    daily = models.ForeignKey('dailies.Daily', on_delete=models.CASCADE)

    title = models.CharField(max_length=50)

    expense = models.DecimalField(max_digits=9, decimal_places=2)

    class Meta(BaseModel.Meta):
        ordering = ['created']

caronte/details/forms/detail.py
# Django
from django import forms
from django.utils.translation import gettext_lazy as _
# Project
from caronte.details.models import Detail
from caronte.utils.forms import IconCharField, IconDecimalField


class DetailForm(forms.ModelForm):

    class Meta:
        model = Detail
        fields = ['title', 'expense']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'] = IconCharField(icon='fas fa-pen', placeholder=_('Description'))
        self.fields['expense'] = IconDecimalField(icon='fas fa-dollar-sign', placeholder=_('Amount'))

caronte/periods/forms/periods.py
"""Periods forms."""

# Python
from datetime import datetime
# Django
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _
# Project
from caronte.periods.models import Period
from caronte.utils.forms import IconDecimalField, IconDateField


class PeriodForm(forms.ModelForm):

    class Meta:
        model = Period
        fields = ['finish_date', 'budget']

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.fields['finish_date'] = IconDateField(icon='fas fa-calendar-alt', placeholder=_('Finish date'))
        self.fields['budget'] = IconDecimalField(icon='fas fa-dollar-sign', placeholder=_('Budget'))

    def clean(self):
        now = datetime.now()
        split_date = self.cleaned_data.get('finish_date').split('-')
        existing_period = Period.objects.current(user=self.user)
        if existing_period:
            raise ValidationError(_('You already have an active Period'))
        errors = ''
        if datetime(int(split_date[0]), int(split_date[1]), int(split_date[2])) <= now:
            errors += _('Period finish date must be after today')
        if float(self.cleaned_data.get('budget')) < 30:
            if errors:
                errors += ', '
            errors += _('Budget cannot be less than $30')
        if errors:
            raise ValidationError(errors)

caronte/users/forms/login.py
# Django
from django import forms
from django.utils.translation import gettext_lazy as _
# Project
from caronte.utils.forms import IconCharField, IconPasswordField


class LoginForm(forms.Form):

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        self.fields['username'] = IconCharField(
            placeholder=_('Username'),
            icon='fas fa-user'
        )

        self.fields['password'] = IconPasswordField(
            placeholder=_('Password'), 
            icon='fas fa-key'
        )

caronte/users/forms/signup.py
# Django
from django import forms
from django.utils.translation import gettext_lazy as _
# Project
from caronte.users.models import User
from caronte.utils.forms import IconCharField, IconEmailField, IconPasswordField


class SignupForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password']

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        self.fields['username'] = IconCharField(
            placeholder=_('Username'),
            icon='fas fa-user-circle'
        )

        self.fields['email'] = IconEmailField(
            placeholder=_('Email'),
            icon='fas fa-at'
        )

        self.fields['first_name'] = IconCharField(
            placeholder=_('First name'),
            icon='fas fa-user-edit'
        )

        self.fields['last_name'] = IconCharField(
            placeholder=_('Last name'),
            icon='fas fa-user-edit'
        )

        self.fields['password'] = IconPasswordField(
            placeholder=_('Password'),
            icon='fas fa-key'
        )

        self.fields['re_password'] = IconPasswordField(
            placeholder=_('Password again'),
            icon='fas fa-key',
            required=False
        )

caronte/utils/forms/icon_fields.py
# Django
from django import forms


class IconCharField(forms.CharField):
    """Django CharField with custom icon attr."""
    
    def __init__(self, *, icon='', placeholder=None, max_length=None,
                 min_length=None, strip=True, empty_value='', **kwargs):
        super().__init__(**kwargs)
        self.icon = icon
        self.widget = forms.TextInput(attrs={'class': 'form-control'})
        if placeholder is not None:
            self.widget.attrs['placeholder'] = placeholder


class IconEmailField(forms.EmailField):
    """Django EmailField with custom icon attr."""
    
    def __init__(self, icon='', placeholder=None, **kwargs):
        super().__init__(**kwargs)
        self.icon = icon
        self.widget = forms.EmailInput(attrs={'class': 'form-control'})
        if placeholder is not None:
            self.widget.attrs['placeholder'] = placeholder


class IconPasswordField(forms.CharField):
    """Django CharField with custom icon attr and password widget."""
    
    def __init__(self, *, icon='', placeholder=None, max_length=None, 
                 min_length=None, strip=True, empty_value='', **kwargs):
        super().__init__(**kwargs)
        self.icon = icon
        self.widget = forms.PasswordInput(attrs={'class': 'form-control'})
        if placeholder is not None:
            self.widget.attrs['placeholder'] = placeholder


class IconDateField(forms.CharField):
    """Django CharField with custom icon attr for dates."""

    def __init__(self, *, icon='', placeholder=None, max_length=None,
                 min_length=None, strip=True, empty_value='', **kwargs):
        super().__init__(**kwargs)
        self.icon = icon
        self.widget = forms.DateInput(attrs={'class': 'form-control', 'type': 'date'})
        if placeholder is not None:
            self.widget.attrs['placeholder'] = placeholder


class IconDecimalField(forms.CharField):
    """Django NumberField with custom icon attr and two decimals."""

    def __init__(self, *, icon='', placeholder=None, max_length=None,
                 min_length=None, strip=True, empty_value='', **kwargs):
        super().__init__(**kwargs)
        self.icon = icon
        self.widget = forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01'})
        if placeholder is not None:
            self.widget.attrs['placeholder'] = placeholder

caronte/details/views/create.py
"""Create Detail views."""

# Django
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views.generic import View
# Project
from caronte.details import services
from caronte.details.forms import DetailForm
from caronte.utils.genericfunctions import form_errors_into_string


class CreateDetailView(View):

    form_model = DetailForm

    def get(self, request, *args, **kwargs):
        return redirect('index:main')

    def post(self, request, *args, **kwargs):
        form = self.form_model(data=request.POST)
        if not form.is_valid():
            errors = form_errors_into_string(form.errors)
            messages.warning(request, errors)
        else:
            detail = services.create(
                user=request.user,
                title=form.cleaned_data.get('title'),
                expense=form.cleaned_data.get('expense')
            )
            if detail:
                messages.success(request, _('Expense added'))
            else:
                messages.error(request, _('Unkown error occurred'))
        return redirect('index:main')

caronte/index/views.py
"""Index views module."""

# Python
import datetime
# Django
from django.shortcuts import render
from django.views import View
# Project
from caronte.details.forms import DetailForm
from caronte.index import services
from caronte.periods.forms import PeriodForm
from caronte.users.forms import SignupForm
from caronte.utils.constants.strings import CARONTE_INDEX_DESCRIPTION


class MainView(View):
    """
    Main view of the application. Display logic conditions are:
        Authenticated user:
            Existent current Period: the current Period, current Daily with its Details, and previous Dailies.
            No current Period: new Period creation template.
        Anonymous user:
            Application info with login an sign up forms.
    """

    period = None
    daily = None

    def get(self, request):
        """
        Handle get request of main index view page.
        If user is authenticated, look for current period, then if a current Period exists, look (or create a new)
        for the current Daily with its Details. If there is no current Period, the page will display a new Period
        form template to create and start a new one.

        @:return render index/main.html with the proper info and template.
        """

        self.period, self.daily = services.handle_index_view(request)

        return render(request, 'index/main.html', {
            'signup_form': SignupForm(),
            'period_form': PeriodForm(),
            'detail_form': DetailForm(),
            'CARONTE_INDEX_DESCRIPTION': CARONTE_INDEX_DESCRIPTION,
            'period': self.period,
            'daily': self.daily,
            'today': datetime.date.today(),
        })

caronte/periods/views/create.py
# Django
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views import View
# Project
from caronte.periods import services
from caronte.periods.forms import PeriodForm
from caronte.utils.genericfunctions import form_errors_into_string


class CreatePeriodView(View):

    form_class = PeriodForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(user=request.user, data=request.POST)
        if form.is_valid():
            period = services.create(
                user=request.user,
                finish_date=form.cleaned_data.get('finish_date'),
                budget=form.cleaned_data.get('budget')
            )
            if period:
                messages.success(request, _('Period started successfully'))
            else:
                messages.error(request, _('Unknown error occurred, please try again'))
        else:
            errors = form_errors_into_string(form.errors)
            messages.warning(request, errors)
        return redirect('index:main')

caronte/users/views/login.py
# Django
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views import View
# Project
from caronte.users import services
from caronte.users.forms import LoginForm


class LoginView(View):
    """Class that receives users' login request."""

    form_class = LoginForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST, prefix='login')
        if form.is_valid():
            user = services.login(
                request=request,
                username=form.cleaned_data.get('username'),
                password=form.cleaned_data.get('password')
            )
            if user is not None:
                messages.success(request, _('You have logged in'))
            else:
                messages.warning(request, _('Wrong username/password'))
        return redirect('index:main')

caronte/users/views/logout.py
# Django
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views import View
# Project
from caronte.users import services


class LogoutView(View):

    @staticmethod
    def get(request):
        if request.user.is_authenticated:
            services.logout(request)
            messages.success(request, _('You have logged out'))
        return redirect('index:main')

caronte/users/views/set_theme.py
# Django
from django.shortcuts import redirect
# Project
from caronte.users.models import User


def set_theme_view(request, theme):
    """
    Set user theme_option in session. Also set value to authenticated user's theme attribute and update user.
    :param request: Django's request
    :param theme: Option to set in session (a/l/d) -> (auto/light/dark)
    :return: redirect to the same page where the request came from, or index's main if theme option is corrupt.
    """
    request.session['theme_option'] = User.Theme(theme).name
    if request.user.is_authenticated:
        request.user.theme = User.Theme(theme)
        request.user.save()
    return redirect(request.META.get('HTTP_REFERER', 'index:main'))

caronte/users/views/signup.py
"""Users signup views."""

# Django
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views import View
# Project
from caronte.users import services
from caronte.users.forms import SignupForm
from caronte.utils.genericfunctions import form_errors_into_string


class SignupView(View):
    """Class that receives users' signup request."""

    form_class = SignupForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            user = services.signup(
                username=form.cleaned_data.get('username'),
                email=form.cleaned_data.get('email'),
                password=form.cleaned_data.get('password'),
                first_name=form.cleaned_data.get('first_name'),
                last_name=form.cleaned_data.get('last_name')
            )
            if user is not None:
                messages.success(request, _('You have registered your account'))
            else:
                messages.error(request, _('Something went wrong, please try again'))
        else:
            errors = form_errors_into_string(form.errors)
            messages.warning(request, errors)
        return redirect('index:main')

caronte/templates/labels.html
{% load i18n %}

<span style="display:none;">
    <span id="oops">{% translate 'Oops' %}</span>
    <span id="passwords_do_not_match">{% translate 'Your passwords do not match!' %}</span>
</span>

caronte/templates/main.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link rel="icon" href="{% static 'favicon.ico' %}">

    <title>Caronte | {% block title %}Inicio{% endblock %}</title>
</head>

<body class="theme-{{ request.session.theme.lower }}">

    {% include 'navbar.html' %}

    {% include 'sidebar.html' %}

    {% include 'notifications_bar.html' %}

    <div class="container mt-2 mt-lg-5">
        {% block content %}{% endblock %}
    </div>

    {% include 'labels.html' %}

    {% include 'footer.html' %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/fontawesome.min.js' %}"></script>
    <script src="{% static 'js/sweetalert2.min.js' %}"></script>
    <script src="{% static 'js/signup.js' %}"></script>
</body>

</html>

caronte/templates/navbar.html
{% load static %}

<header class="navbar navbar-expand-md navbar-dark bg-dark sticky-top bd-navbar">

    <nav class="container-xxl flex-wrap flex-md-nowrap" aria-label="Main navigation">

        <a class="navbar-brand" href="{% url 'index:main' %}">
            Caronte
        </a>

        {% if user.is_authenticated %}
            {% include 'navbar_authenticated.html' %}
        {% else %}

            <div class="d-md-none">
                {% include 'navbar_theme_button.html' %}
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% include 'navbar_anonymous.html' %}
            </div>
            <div class="d-none d-md-block">
                {% include 'navbar_theme_button.html' %}
            </div>
        {% endif %}

    </nav>

</header>

caronte/templates/navbar_anonymous.html
{% load i18n %}

<form class="navbar-nav" method="POST" action="{% url 'users:login' %}" enctype="application/x-www-form-urlencoded">
    <div class="row">
    {% csrf_token %}
        {% for field in request.login_form %}
            <div class="col-12 col-md-5 my-1 my-md-0">
                <div class="input-group">
                    <div class="input-group-text">
                        <i class="{{ field.field.icon }} mx-auto"></i>
                    </div>
                    {{ field }}
                </div>
            </div>
        {% endfor %}
        <div class="col-12 col-md-2 my-1 my-md-0 d-grid">
            <button type="submit" class="btn btn-outline-light">{% translate 'Login' %}</button>
        </div>
    </div>
</form>

caronte/templates/navbar_authenticated.html
{% load static %}

{% include 'navbar_theme_button.html' %}
<a href="{% url 'users:logout' %}" class="btn btn-light">
    <i class="fas fa-door-open"></i>
</a>

caronte/templates/navbar_login.html
{% load i18n %}

<form class="navbar-nav" method="POST" action="{% url 'users:login' %}" enctype="application/x-www-form-urlencoded">
    <div class="row">
    {% csrf_token %}
        {% for field in request.login_form %}
            <div class="col-12 col-md-5 my-1 my-md-0">
                <div class="input-group">
                    <div class="input-group-text">
                        <i class="{{ field.field.icon }} mx-auto"></i>
                    </div>
                    {{ field }}
                </div>
            </div>
        {% endfor %}
        <div class="col-12 col-md-2 my-1 my-md-0 d-grid">
            <button type="submit" class="btn btn-outline-light">{% translate 'Login' %}</button>
        </div>
    </div>
</form>

caronte/templates/navbar_theme_button.html
{% load i18n %}

<div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-{% if request.session.theme.lower == 'light' %}sun{% else %}moon{% endif %}"></i>
        </button>
    <ul class="dropdown-menu {% if request.session.theme.lower == 'dark' %}dropdown-menu-dark{% endif %} dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
        <li><a class="dropdown-item" href="{% url 'users:set_theme' 'a' %}"><i class="fas fa-sync-alt"></i> {% translate 'Auto' %}</a></li>
        <li><a class="dropdown-item" href="{% url 'users:set_theme' 'l' %}"><i class="fas fa-sun"></i> {% translate 'Light' %}</a></li>
        <li><a class="dropdown-item" href="{% url 'users:set_theme' 'd' %}"><i class="fas fa-moon"></i> {% translate 'Dark' %}</a></li>
    </ul>
</div>

caronte/templates/notifications_bar.html
{% if messages %}

{% for message in messages %}
<div class="alert alert-{{ message.tags}} text-center alert-dismissible fade show" role="alert">
    {{ message|capfirst }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

{% endif %}